package cn.iocoder.yudao.module.finance.service.payment;

import cn.iocoder.yudao.framework.tenant.config.TenantProperties;
import cn.iocoder.yudao.framework.tenant.core.context.TenantContextHolder;
import cn.iocoder.yudao.framework.tenant.core.db.TenantDatabaseInterceptor;
import cn.iocoder.yudao.framework.tenant.core.util.TenantUtils;
import cn.iocoder.yudao.module.finance.dal.dataobject.customer.FinanceCustomerCompanyDO;
import cn.iocoder.yudao.module.finance.dal.dataobject.payment.FinancePaymentApplicationDO;
import cn.iocoder.yudao.module.finance.dal.mysql.customer.FinanceCustomerCompanyMapper;
import cn.iocoder.yudao.module.finance.dal.mysql.payment.FinancePaymentApplicationMapper;
import cn.iocoder.yudao.module.finance.enums.FinancePaymentApplicationStatusEnum;
import com.baomidou.mybatisplus.core.MybatisConfiguration;
import com.baomidou.mybatisplus.core.MybatisSqlSessionFactoryBuilder;
import com.baomidou.mybatisplus.core.config.GlobalConfig;
import com.baomidou.mybatisplus.core.toolkit.GlobalConfigUtils;
import com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor;
import com.baomidou.mybatisplus.extension.plugins.inner.TenantLineInnerInterceptor;
import org.apache.ibatis.mapping.Environment;
import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;
import org.apache.ibatis.transaction.jdbc.JdbcTransactionFactory;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.Collections;

import static org.junit.jupiter.api.Assertions.*;

/**
 * PAY-R17：H2 + 真实 Mapper + 生产 {@link TenantDatabaseInterceptor} 跨租户空结果证据。
 * <p>禁止 mock mapper；禁止仅 parserSingle 文本 diff。
 */
class FinancePaymentRealCrossTenantAbTest {

    private static final long TENANT_A = 100L;
    private static final long TENANT_B = 200L;

    private static SqlSessionFactory sqlSessionFactory;

    @BeforeAll
    static void init() throws Exception {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:pay_r17_tenant;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;NON_KEYWORDS=VALUE");
        dataSource.setUser("sa");
        dataSource.setPassword("");

        try (Connection conn = dataSource.getConnection(); Statement st = conn.createStatement()) {
            st.execute("DROP TABLE IF EXISTS finance_payment_application");
            st.execute("DROP TABLE IF EXISTS finance_customer_company");
            st.execute("""
                    CREATE TABLE finance_payment_application (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      application_no VARCHAR(64),
                      process_instance_id VARCHAR(64),
                      status VARCHAR(32),
                      current_node_key VARCHAR(64),
                      current_node_name VARCHAR(128),
                      process_title VARCHAR(255),
                      applicant_user_id BIGINT,
                      applicant_dept_id BIGINT,
                      apply_date DATE,
                      payment_timing VARCHAR(32),
                      payment_reason VARCHAR(32),
                      purchase_process_instance_id VARCHAR(64),
                      purchase_snapshot VARCHAR(1024),
                      lease_contract_application_id BIGINT,
                      related_contract_application_id BIGINT,
                      payee_company_id BIGINT,
                      payee_name VARCHAR(255),
                      payee_bank_name VARCHAR(255),
                      payee_bank_account VARCHAR(128),
                      apply_amount DECIMAL(18,2),
                      currency VARCHAR(16),
                      amount_in_words VARCHAR(128),
                      contract_settlement_method VARCHAR(64),
                      business_settlement_term VARCHAR(255),
                      pay_method VARCHAR(32),
                      cost_project VARCHAR(64),
                      accounting_subject VARCHAR(64),
                      evidence_file_urls VARCHAR(2048),
                      special_note VARCHAR(1000),
                      actual_pay_date DATE,
                      pay_voucher_url VARCHAR(1024),
                      erp_voucher_no VARCHAR(64),
                      voided BOOLEAN DEFAULT FALSE,
                      creator VARCHAR(64),
                      create_time TIMESTAMP,
                      updater VARCHAR(64),
                      update_time TIMESTAMP,
                      deleted BOOLEAN DEFAULT FALSE,
                      tenant_id BIGINT NOT NULL
                    )
                    """);
            st.execute("""
                    CREATE TABLE finance_customer_company (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      code VARCHAR(64),
                      name VARCHAR(255),
                      tax_no VARCHAR(64),
                      bank_name VARCHAR(255),
                      bank_account VARCHAR(128),
                      address VARCHAR(512),
                      phone VARCHAR(64),
                      contact_name VARCHAR(128),
                      email VARCHAR(128),
                      status INT,
                      is_customer BOOLEAN,
                      is_supplier BOOLEAN,
                      party_type VARCHAR(32),
                      creator VARCHAR(64),
                      create_time TIMESTAMP,
                      updater VARCHAR(64),
                      update_time TIMESTAMP,
                      deleted BOOLEAN DEFAULT FALSE,
                      tenant_id BIGINT NOT NULL
                    )
                    """);
        }

        MybatisConfiguration configuration = new MybatisConfiguration();
        configuration.setMapUnderscoreToCamelCase(true);
        configuration.setCacheEnabled(false);
        configuration.setEnvironment(new Environment("r17", new JdbcTransactionFactory(), dataSource));

        GlobalConfig globalConfig = new GlobalConfig();
        GlobalConfig.DbConfig dbConfig = new GlobalConfig.DbConfig();
        dbConfig.setLogicDeleteField("deleted");
        dbConfig.setLogicDeleteValue("true");
        dbConfig.setLogicNotDeleteValue("false");
        globalConfig.setDbConfig(dbConfig);
        GlobalConfigUtils.setGlobalConfig(configuration, globalConfig);

        // 生产 TenantLine 路径（与 YudaoTenantAutoConfiguration 一致）
        TenantProperties props = new TenantProperties();
        props.setIgnoreTables(Collections.emptySet());
        MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
        interceptor.addInnerInterceptor(new TenantLineInnerInterceptor(new TenantDatabaseInterceptor(props)));
        configuration.addInterceptor(interceptor);

        configuration.addMapper(FinancePaymentApplicationMapper.class);
        configuration.addMapper(FinanceCustomerCompanyMapper.class);

        sqlSessionFactory = new MybatisSqlSessionFactoryBuilder().build(configuration);
    }

    @AfterEach
    void clearTenantAndData() throws Exception {
        TenantContextHolder.clear();
        try (SqlSession session = sqlSessionFactory.openSession(true)) {
            Connection conn = session.getConnection();
            try (Statement st = conn.createStatement()) {
                st.execute("DELETE FROM finance_payment_application");
                st.execute("DELETE FROM finance_customer_company");
            }
        }
    }

    @Test
    void tenantA_insertPayment_rowHasTenantA() {
        Long id = TenantUtils.execute(TENANT_A, () -> {
            try (SqlSession session = sqlSessionFactory.openSession(true)) {
                FinancePaymentApplicationMapper mapper = session.getMapper(FinancePaymentApplicationMapper.class);
                FinancePaymentApplicationDO row = paidPayment("PAY-A-1", 9L, "100.00");
                assertEquals(1, mapper.insert(row));
                assertNotNull(row.getId());
                FinancePaymentApplicationDO loaded = mapper.selectById(row.getId());
                assertNotNull(loaded);
                assertEquals(TENANT_A, loaded.getTenantId());
                return row.getId();
            }
        });
        assertNotNull(id);
    }

    @Test
    void tenantB_selectById_ofTenantA_isNull() {
        Long aId = TenantUtils.execute(TENANT_A, () -> {
            try (SqlSession session = sqlSessionFactory.openSession(true)) {
                FinancePaymentApplicationMapper mapper = session.getMapper(FinancePaymentApplicationMapper.class);
                FinancePaymentApplicationDO row = paidPayment("PAY-A-2", 9L, "50.00");
                mapper.insert(row);
                return row.getId();
            }
        });

        // 正对照：A 仍可见
        FinancePaymentApplicationDO aSee = TenantUtils.execute(TENANT_A, () -> {
            try (SqlSession session = sqlSessionFactory.openSession(true)) {
                return session.getMapper(FinancePaymentApplicationMapper.class).selectById(aId);
            }
        });
        assertNotNull(aSee);
        assertEquals(TENANT_A, aSee.getTenantId());

        // B 不可见
        FinancePaymentApplicationDO bSee = TenantUtils.execute(TENANT_B, () -> {
            try (SqlSession session = sqlSessionFactory.openSession(true)) {
                return session.getMapper(FinancePaymentApplicationMapper.class).selectById(aId);
            }
        });
        assertNull(bSee, "tenant B must not select tenant A payment id=" + aId);
    }

    @Test
    void tenantB_sumPaidByPayee_excludesTenantA() {
        TenantUtils.execute(TENANT_A, () -> {
            try (SqlSession session = sqlSessionFactory.openSession(true)) {
                FinancePaymentApplicationMapper mapper = session.getMapper(FinancePaymentApplicationMapper.class);
                mapper.insert(paidPayment("PAY-A-SUM", 9L, "88.50"));
                BigDecimal sumA = mapper.sumPaidByPayee(9L);
                assertEquals(0, new BigDecimal("88.50").compareTo(sumA));
                return null;
            }
        });

        BigDecimal sumB = TenantUtils.execute(TENANT_B, () -> {
            try (SqlSession session = sqlSessionFactory.openSession(true)) {
                return session.getMapper(FinancePaymentApplicationMapper.class).sumPaidByPayee(9L);
            }
        });
        assertNotNull(sumB);
        assertEquals(0, BigDecimal.ZERO.compareTo(sumB),
                "tenant B sumPaid must exclude A rows, got " + sumB);
    }

    @Test
    void tenantB_selectCustomer_ofTenantA_isNull() {
        Long customerId = TenantUtils.execute(TENANT_A, () -> {
            try (SqlSession session = sqlSessionFactory.openSession(true)) {
                FinanceCustomerCompanyMapper mapper = session.getMapper(FinanceCustomerCompanyMapper.class);
                FinanceCustomerCompanyDO company = FinanceCustomerCompanyDO.builder()
                        .code("SUP-A")
                        .name("供应商甲")
                        .taxNo("91110000A")
                        .bankName("行")
                        .bankAccount("6222")
                        .status(FinanceCustomerCompanyDO.STATUS_ENABLE)
                        .isCustomer(false)
                        .isSupplier(true)
                        .build();
                company.setDeleted(false);
                assertEquals(1, mapper.insert(company));
                FinanceCustomerCompanyDO loaded = mapper.selectById(company.getId());
                assertNotNull(loaded);
                assertEquals(TENANT_A, loaded.getTenantId());
                return company.getId();
            }
        });

        FinanceCustomerCompanyDO bSee = TenantUtils.execute(TENANT_B, () -> {
            try (SqlSession session = sqlSessionFactory.openSession(true)) {
                return session.getMapper(FinanceCustomerCompanyMapper.class).selectById(customerId);
            }
        });
        assertNull(bSee, "tenant B must not select tenant A customer id=" + customerId);
    }

    private static FinancePaymentApplicationDO paidPayment(String no, long payeeId, String amount) {
        FinancePaymentApplicationDO row = FinancePaymentApplicationDO.builder()
                .applicationNo(no)
                .status(FinancePaymentApplicationStatusEnum.PAID.getStatus())
                .applicantUserId(1L)
                .applyDate(LocalDate.of(2026, 8, 6))
                .paymentTiming("IMMEDIATE")
                .paymentReason("BUSINESS")
                .payeeCompanyId(payeeId)
                .payeeName("供应商甲")
                .payeeBankName("行")
                .payeeBankAccount("6222")
                .applyAmount(new BigDecimal(amount))
                .currency("CNY")
                .businessSettlementTerm("月结")
                .payMethod("TRANSFER")
                .costProject("OP")
                .evidenceFileUrls("[]")
                .voided(false)
                .build();
        row.setDeleted(false);
        return row;
    }
}
